2024-12-18 12:25:50,157 - main.py - initialize_controller - ERROR - Error initializing controller: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6762b1204b571b5cd817fd27, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-12-18 12:25:50,161 - main.py - main - CRITICAL - Critical error in main: No module named 'adafruit_dht'
2024-12-18 12:26:39,176 - main.py - initialize_controller - ERROR - Error initializing controller: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6762b151099ad5ea0832afa9, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-12-18 12:26:39,189 - database_service.py - initialize_plants - ERROR - Error initializing plants: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:27:09,335 - main.py - start_services - ERROR - Failed to start all services: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6762b151099ad5ea0832afa9, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-12-18 12:27:09,342 - database_service.py - initialize_plants - ERROR - Error initializing plants: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:28:09,351 - main.py - check_and_restart - ERROR - Database service restart failed.
2024-12-18 12:28:09,352 - main.py - check_service_health - ERROR - Full service restart required.
2024-12-18 12:28:10,361 - database_service.py - initialize_plants - ERROR - Error initializing plants: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:50,339 - database_service.py - initialize_plants - ERROR - Error initializing plants: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:50,391 - irrigation_service.py - initialize_last_watered_times - ERROR - Error initializing last watered times: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:50,535 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:50,535 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:51,560 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:51,564 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:52,587 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:52,589 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:53,615 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:53,619 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:54,644 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:54,645 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:30:54,648 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:55,673 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:55,674 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:30:55,677 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:56,702 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:56,703 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:30:56,709 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:57,734 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:57,735 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:30:57,737 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:58,760 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:58,761 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:30:58,765 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:59,790 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:30:59,791 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:30:59,797 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:00,990 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:00,991 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:00,994 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:02,018 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:02,019 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:02,022 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:03,047 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:03,048 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:03,051 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:04,076 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:04,077 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:04,081 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:05,106 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:05,107 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:05,110 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:06,137 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:06,138 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:06,141 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:07,166 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:07,167 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:07,171 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:08,193 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:08,194 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:08,195 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:09,219 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:09,220 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:09,224 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:10,249 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:10,250 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:10,254 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:11,297 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:11,298 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:11,298 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:12,319 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:12,319 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:12,320 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:13,340 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:13,341 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:13,342 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:40,291 - database_service.py - initialize_plants - ERROR - Error initializing plants: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:40,347 - irrigation_service.py - initialize_last_watered_times - ERROR - Error initializing last watered times: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:40,475 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:40,476 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:41,501 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:41,504 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:42,529 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:42,532 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:43,556 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:43,560 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:44,583 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:44,584 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:44,587 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:45,612 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:45,614 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:45,617 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:46,641 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:46,642 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:46,645 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:47,670 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:47,671 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:47,673 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:48,695 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:48,695 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:48,696 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:49,720 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:49,721 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:49,724 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:50,955 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:50,956 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:50,958 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:51,983 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:51,984 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:51,987 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:53,012 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:53,013 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:53,015 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:54,038 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:54,039 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:54,041 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:55,065 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:55,067 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:55,070 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:56,095 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:56,096 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:56,099 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:57,124 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:57,125 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:57,129 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:58,154 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:58,155 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:58,159 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:59,184 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:31:59,185 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:31:59,188 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:00,213 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:00,214 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:32:00,217 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:01,278 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:01,279 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:32:01,282 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:02,307 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:02,308 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:32:02,311 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:03,336 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:03,337 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:32:03,340 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:04,366 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:04,367 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:32:04,371 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:05,396 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:05,397 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:32:05,400 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:06,425 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:06,427 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:32:06,429 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:07,451 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:32:07,451 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:32:07,452 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:37,100 - database_service.py - initialize_plants - ERROR - Error initializing plants: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:37,148 - irrigation_service.py - initialize_last_watered_times - ERROR - Error initializing last watered times: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:37,304 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:37,308 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:38,330 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:38,331 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:39,355 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:39,359 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:40,383 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:40,386 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:41,411 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:41,412 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:41,416 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:42,441 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:42,442 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:42,445 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:43,467 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:43,467 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:43,467 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:44,489 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:44,490 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:44,491 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:45,515 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:45,515 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:45,518 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:46,543 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:46,544 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:46,546 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:47,741 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:47,742 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:47,745 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:48,770 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:48,772 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:48,776 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:49,800 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:49,801 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:49,804 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:50,829 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:50,830 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:50,833 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:51,858 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:51,859 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:51,859 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:52,882 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:33:52,883 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:33:52,885 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:34,662 - database_service.py - initialize_plants - ERROR - Error initializing plants: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:34,711 - irrigation_service.py - initialize_last_watered_times - ERROR - Error initializing last watered times: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:34,862 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:34,868 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:35,894 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:35,899 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:36,925 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:36,929 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:37,951 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:37,952 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:38,976 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:38,976 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:38,978 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:40,000 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:40,001 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:40,003 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:41,028 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:41,030 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:41,034 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:42,060 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:42,063 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:42,065 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:43,092 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:43,093 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:43,097 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:44,123 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:44,124 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:44,129 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:45,322 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:45,322 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:45,325 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:46,347 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:46,347 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:46,348 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:47,373 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:47,374 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:47,379 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:48,405 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:48,406 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:48,410 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:49,437 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:49,438 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:49,442 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:50,468 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:50,469 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:50,474 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:51,500 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:51,501 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:51,505 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:52,530 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:52,532 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:52,535 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:53,559 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:53,559 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:53,562 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:54,586 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:54,587 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:54,591 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:55,643 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:55,643 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:55,644 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:56,669 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:56,670 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:56,674 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:57,701 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:57,702 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:57,706 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:58,732 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:58,733 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:58,737 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:59,762 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:35:59,763 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:35:59,767 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:00,793 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:00,794 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:36:00,797 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:01,823 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:01,824 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:36:01,829 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:02,851 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:02,851 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 12:36:02,852 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:39,739 - database_service.py - initialize_plants - ERROR - Error initializing plants: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:39,796 - irrigation_service.py - initialize_last_watered_times - ERROR - Error initializing last watered times: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:39,953 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:50,473 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:51,670 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:58,522 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 12:36:59,549 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:11,854 - database_service.py - initialize_plants - ERROR - Error initializing plants: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:11,907 - irrigation_service.py - initialize_last_watered_times - ERROR - Error initializing last watered times: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:12,063 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:12,067 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:13,089 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:13,091 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:14,115 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:14,118 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:15,144 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:15,147 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:16,173 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:16,174 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:16,177 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:17,206 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:17,209 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:17,213 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:18,235 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:18,236 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:18,237 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:19,257 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:19,258 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:19,258 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:20,283 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:20,284 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:20,287 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:21,312 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:21,313 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:21,316 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:22,510 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:22,511 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:22,512 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:23,537 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:23,538 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:23,541 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:24,567 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:24,569 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:24,572 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:25,597 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:25,598 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:25,602 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:26,627 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:26,628 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:26,631 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:27,655 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:27,655 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:27,657 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:28,682 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:28,683 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:28,686 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:29,710 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:29,711 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:29,713 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:30,737 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:30,738 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:30,741 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:31,767 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:31,769 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:31,772 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:32,828 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:32,828 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:32,831 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:33,857 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:33,859 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:33,863 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:34,885 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:34,886 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:34,888 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:35,913 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:35,913 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:35,915 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:36,940 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:36,941 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:36,944 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:37,967 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:37,967 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:37,969 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:38,994 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:38,995 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:38,999 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:40,022 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:40,022 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:40,023 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:41,046 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:41,047 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:41,051 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:42,075 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:42,076 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:42,079 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:43,126 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:43,127 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:43,128 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:44,152 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:44,153 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:44,157 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:45,180 - database_service.py - save_sensor_data - ERROR - Unexpected error: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2024-12-18 20:45:45,181 - database_service.py - increment_exception_count - ERROR - Too many errors within a short period. Marking as unhealthy.
2024-12-18 20:45:45,185 - database_service.py - save_watering_logs - ERROR - Error processing watering logs: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-03-02 16:53:02,276 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
2025-03-02 16:53:07,291 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
2025-03-02 16:53:12,303 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
2025-03-02 16:53:17,317 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
2025-03-02 16:54:01,889 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
2025-03-02 16:54:06,925 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
2025-03-02 16:54:11,939 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
2025-03-02 16:54:16,954 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
2025-03-02 16:54:21,965 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
2025-03-02 16:54:26,979 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
2025-03-02 16:54:31,992 - database.py - connect - ERROR - Failed to connect to MongoDB: The DNS query name does not exist: _mongodb._tcp.cluster0.pdaqcm3.mongodb.net.. Retrying in 5 seconds...
